#!/usr/bin/env python

import sys
from os import path

from vendorize import vendorize_requirement, vendorize_requirements


def main():
    if len(sys.argv) < 2:
        if not path.isfile("vendorize.toml") and path.isfile("pyproject.toml"):
            vendorize_requirements(path="pyproject.toml")
        else:
            # keep old behavior even if vendorize.toml doesnt exist
            vendorize_requirements(path="vendorize.toml")

    elif len(sys.argv) < 3:
        vendorize_requirements(path=sys.argv[1])
    else:
        requirement = sys.argv[1]
        target_directory = sys.argv[2]
        vendorize_requirement(cwd=".", requirement=requirement, target_directory=target_directory)


if __name__ == "__main__":
    main()
